baseurl: "/"
title: "Mike Sturm"
init_js: "js/init.js"
params:
  header:
    title: Mike Sturm
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: Generic
        url: /generic/
      - label: Elements
        url: /elements/
      - label: Ipsum
        url: /ipsum/
  footer:
    content: >-
      &copy; Mike Sturm. All rights reserved.
    has_social: true
    social_links:
      - label: Twitter
        url: https://twitter.com/
        new_window: true
      - label: Instagram
        url: https://www.instagram.com/
        new_window: true
      - label: GitHub
        url: https://github.com/
        new_window: true
      - label: LinkedIn
        url: https://www.linkedin.com/
        new_window: true
      - label: DEV
        url: https://dev.to/
        new_window: true
sass:
  input_file: sass/main.scss
  output_file: css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
